name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Denver
          base: header, repositories
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 365
          plugin_code: yes
          plugin_stars: yes
          plugin_notable: yes
          plugin_lines: yes
          config_display: large
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_calendar: yes
          plugin_activity: yes
